version: '3'
services:

  mysql:
    container_name: demomysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Alch3mist
      - MYSQL_DATABASE=sakila
    volumes:
      - ./init-mysql:/docker-entrypoint-initdb.d

  postgre:
    container_name: demopostgre
    image: postgres:14.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Alch3mist
      - POSTGRES_DB=postgres
    volumes:
      - ./init-postgre:/docker-entrypoint-initdb.d